# Generated by Django 4.0.3 on 2022-10-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
