# Generated by Django 4.0.3 on 2022-10-13 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0004_rename_last_menstural_data_user_data_last_menstural_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='user_id',
        ),
    ]
