# Generated by Django 4.0.3 on 2022-10-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0005_remove_user_data_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
